### ISSUE TITLE
[halp me]

### ISSUE THREAD

**Issue by itz63c** [RaphielGang/Telegram-UserBot#129]
**Describe the bug**

**To Reproduce**
any functions needing database connections are failing on 3.0 alpha
**Expected behavior**
things to work

**Screenshots**
https://i.imgur.com/IRReewQ.png this was trying to use the .mute command
.alive also shows this https://i.imgur.com/65iRxU4.png

**Python Version**
3.7.3

**Comment by baalajimaestro** [comment]
Please check if you can manually connect to either of the databases, seems like the python drivers couldn't connect. Make sure you followed the guide for database setup in the wiki.
