### ISSUE TITLE
Having issues getting the bot to properly connect to mongo db

### ISSUE THREAD

**Issue by itz63c** [RaphielGang/Telegram-UserBot#140]
**Describe the bug**
mongo db issues

**To Reproduce**
i followed the steps on the readme... and mongodb atlas says i am connected to the database but the bot says i am not

Your bot is running 

Telethon version: 1.8.0 
Python: 3.7.3 
User: BeeldBox 
Database Status: Either Mongo or Redis Database seems to be failing!

**Expected behavior**
Database Status: to not say there is error.... no commands that use the database seem to work either

**Screenshots**
![image](https://user-images.githubusercontent.com/44932193/59969309-5471ab00-9518-11e9-99bc-fb841ac707eb.png)
![image](https://user-images.githubusercontent.com/44932193/59969312-6c492f00-9518-11e9-83bd-08e833af32cb.png)

**Python Version**
3.7.3

**Additional context**

**Comment by itz63c** [comment]
wtf

**Comment by RWN-N** [comment]
DId u find out the way? @itz63c
