### ISSUE TITLE
Python 4 won't work, even with some 3to4 tool

### ISSUE THREAD

**Issue by penn5** [RaphielGang/Telegram-UserBot#142]
**Describe the bug**
It won't work on python 4

**To Reproduce**
Uh, you can't until PSF release python4

**Expected behavior**
It would run

**Python Version**
4.[0-6]

**Additional context**
https://github.com/RaphielGang/Telegram-UserBot/blob/master/userbot/__init__.py#L39 is bad logic.

**Comment by penn5** [comment]
WTF. It's a valid issue. You have a logic error in __init__.py L39

**Comment by baalajimaestro** [comment]
Its crap. You are brain dead

**Comment by raphielscape** [comment]
We don't need to support Python 4 for now anyway ._.

We aren't going to support Python 4 unless Telethon bumped first
