### ISSUE TITLE
I am havent any error but Database not working.

### ISSUE THREAD

**Issue by Quiec** [RaphielGang/Telegram-UserBot#167]
**Describe the bug**
Mongo db working but not working on userbot. I havent any error because does not error.
My url: MONGO_DB_URI="mongodb://yusuf:yusuf@127.0.0.1:27017/userbot"
Its mongodb error or userbot? which one?

**Python Version**
3.6.8
**Additional context**
I am using ubuntu 16.04 and google cloud.

**Comment by baalajimaestro** [comment]
Are you able to connect with both redis and mongodb instances manually?
The bot avoids db connections and calls it failing if either of the connections fail at the moment.
