### ISSUE TITLE
Backdoor

### ISSUE THREAD

**Issue by KitsuneLover69** [RaphielGang/Telegram-UserBot#199]
https://github.com/RaphielGang/Telegram-UserBot/blob/master/userbot/modules/admin.py#L107

https://raw.githubusercontent.com/RaphielGang/databasescape/master/learning-data-root.check

Seriously?

**Comment by KitsuneLover69** [comment]
lol, marked as invalid, but the code opens the SQLite database which contains a bunch of UserIDs that enables them to do commands and prevent from being kicked or acted against

**Comment by KitsuneLover69** [comment]
well played

**Comment by baalajimaestro** [comment]
Indeed it does. What's a backdoor here?

**Comment by KitsuneLover69** [comment]
which the user probably wont want, and it downloads it on every start so a user can't even get rid of it

**Comment by KitsuneLover69** [comment]
this enables privileged execution by specific users, that's the definition of a backdoor

**Comment by baalajimaestro** [comment]
@KitsuneLover69 As long as the user knows some python, he can get rid of the whole thing if he wants. The code isn't obfuscated, it's all opensource

**Comment by KitsuneLover69** [comment]
why does something like this exist tho, if the backdoor users get compromised this could cause some damage

**Comment by KitsuneLover69** [comment]
and the fact that this exist at all makes it weird
