### ISSUE TITLE
.img command always errors

### ISSUE THREAD

**Issue by watzon** [RaphielGang/Telegram-UserBot#200]
**Describe the bug**
Everytime I use the `.img` command it returns an error.

**To Reproduce**
Send `.img donald trump meme` or any other query

**Expected behavior**
Images should be returned with no error

**Python Version**
Using baalajimaestro/userbot_python:latest, so the version in there

**Additional context**
It seems as though there are two types of errors. One looks like this

```
Traceback info:
Traceback (most recent call last):
  File "/app/userbot/events.py", line 80, in wrapper
    await func(check)
  File "/app/userbot/modules/scrapers.py", line 66, in img_sampler
    os.rmdir(os.path.dirname(os.path.abspath(lst[0])))
OSError: [Errno 39] Directory not empty: '/app/downloads'
```

The other occurs when adding a limit to the number of images using `lim=5` in the query

```
Traceback info:
Traceback (most recent call last):
  File "/app/userbot/events.py", line 80, in wrapper
    await func(check)
  File "/app/userbot/modules/scrapers.py", line 65, in img_sampler
    os.remove(lst[1])
IndexError: list index out of range
```

**Comment by raphielscape** [comment]
Fixed as-per https://github.com/RaphielGang/Telegram-UserBot/commit/58382655b18a1edc97d324cb9bd2d2cb0185e436

Try to move your repo to staging and report.

**Comment by watzon** [comment]
Awesome I actually just made the same change in my fork and it worked. I was going to suggest it here. Closing.
