### ISSUE TITLE
Heroku Push failing

### ISSUE THREAD

**Issue by linuxandria** [RaphielGang/Telegram-UserBot#217]
**Describe the bug**
Heroku push fails, stating some file is missing from /var/lib/docker

**To Reproduce**
1. Follow normal setup
2. Try to push to heroku

**Expected behavior**
Pushes successfully

**Screenshots**
N/A

**Python Version**
3.8.1

**Additional context**
```
remote: Step 5/6 : COPY ./userbot.session ./config.env* ./client_secrets.json* ./secret.json* /app/
remote: COPY failed: stat /var/lib/docker/tmp/docker-builder304893055/userbot.session: no such file or directory
```
I did run generate_session.py and userbot.session exists locally

**Comment by nysascape** [comment]
View .gitignore, it won't be included in a commit
You actually need to push this file to Heroku.

The wiki instructions are really not clear as of this time. I'm planning to rewrite it.

**Comment by linuxandria** [comment]
Ok tyvm
